# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false

language: node_js
node_js:
  - 6

before_install:
  - npm install typings --global

install:
  - npm install
  - typings install

script:
  - npm run build

branches:
  only:
    - master            # only run CI on the master branch
    - /^FR /            # also build pull requests

after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js # send code-coverage data to Coveralls